version: '3.0'

services:
  grafana:
    container_name: 'ifrost-toggltrack-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.3.8}
    ports:
      - 3001:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/ifrost-toggltrack-datasource
      - ./provisioning:/etc/grafana/provisioning
